#include <bits/stdc++.h>
using namespace std;

int main() {
	// freopen("test.in", "rt", stdin);
	ios::sync_with_stdio(false);

	string vigenere_square[26] =
	{ "BCDEFGHIJKLMNOPQRSTUVWXYZA",
	  "CDEFGHIJKLMNOPQRSTUVWXYZAB",
	  "DEFGHIJKLMNOPQRSTUVWXYZABC",
	  "EFGHIJKLMNOPQRSTUVWXYZABCD",
	  "FGHIJKLMNOPQRSTUVWXYZABCDE",
	  "GHIJKLMNOPQRSTUVWXYZABCDEF",
	  "HIJKLMNOPQRSTUVWXYZABCDEFG",
	  "IJKLMNOPQRSTUVWXYZABCDEFGH",
	  "JKLMNOPQRSTUVWXYZABCDEFGHI",
	  "KLMNOPQRSTUVWXYZABCDEFGHIJ",
	  "LMNOPQRSTUVWXYZABCDEFGHIJK",
	  "MNOPQRSTUVWXYZABCDEFGHIJKL",
	  "NOPQRSTUVWXYZABCDEFGHIJKLM",
	  "OPQRSTUVWXYZABCDEFGHIJKLMN",
	  "PQRSTUVWXYZABCDEFGHIJKLMNO",
	  "QRSTUVWXYZABCDEFGHIJKLMNOP",
	  "RSTUVWXYZABCDEFGHIJKLMNOPQ",
	  "STUVWXYZABCDEFGHIJKLMNOPQR",
	  "TUVWXYZABCDEFGHIJKLMNOPQRS",
	  "UVWXYZABCDEFGHIJKLMNOPQRST",
	  "VWXYZABCDEFGHIJKLMNOPQRSTU",
	  "WXYZABCDEFGHIJKLMNOPQRSTUV",
	  "XYZABCDEFGHIJKLMNOPQRSTUVW",
	  "YZABCDEFGHIJKLMNOPQRSTUVWX",
	  "ZABCDEFGHIJKLMNOPQRSTUVWXY",
	  "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	};

	string s, t;
	int n, m;

	while (1) {
		cin >> s;
		if (s == "0") {
			break;
		}
		cin >> t;
		n = s.length();
		m = t.length();
		for (int i = 0; i < m; i++) {
			t[i] = vigenere_square[t[i] - 'A'][s[i % n] - 'A'];
		}
		cout << t << "\n";
	}

	return 0;
}